version: "3.8"
services:

    # PHP service
    app:
        build: ./Docker
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # MySQL database service
#    db:
#        image: mysql:5.7
#        container_name: mysql-db
#        ports:
#            - "3306:3306"
#        environment:
#            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#            MYSQL_DATABASE: ${DB_DATABASE}
#            MYSQL_USER: ${DB_USERNAME}
#            MYSQL_PASSWORD: ${DB_PASSWORD}
#        env_file:
#            - ./.env
#        networks:
#            - app-network


    db:
        container_name: db
        image: mysql
        restart: always
        #    environment:
        #      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
        #      MYSQL_DATABASE: php-app
        #      MYSQL_USER: USER
        #      MYSQL_PASSWORD: PASS
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        ports:
            - "3306:3306"
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

#php myadmin
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
        restart: always
        ports:
            - 8081:80
        networks:
            - app-network



networks:
    app-network:
        driver: bridge
